### ISSUE TITLE
Stage1 Not able to run 3D Shape Generation

### ISSUE THREAD

**Issue by zxhxixi** [liuzhengzhe/EXIM#4]
pretrained model doesnot march the code in stage1 
RuntimeError: Error(s) in loading state_dict for UNet3DConditionModel:
        Unexpected key(s) in state_dict: "clip_model.text_model.embeddings.position_ids", "clip_model.vision_model.embeddings.position_ids", "clip.embeddings.position_ids".

**Comment by liuzhengzhe** [comment]
Thanks for the question. It is due to the transformers version. 

pip install transformers==4.28.1
